export const katexMacros: Record<string, string> = {
  '\\ket': '\\left|#1\\right\\rangle',
  '\\bra': '\\left\\langle#1\\right|',
  '\\braket': '\\left\\langle#1|#2\\right\\rangle',
  '\\inner': '\\left\\langle#1,#2\\right\\rangle',
  '\\norm': '\\left\\|#1\\right\\|',
  '\\abs': '\\left|#1\\right|',
  '\\tr': '\\operatorname{tr}',
  '\\Tr': '\\operatorname{Tr}',
  '\\CNOT': '\\operatorname{CNOT}',
  '\\Prob': '\\operatorname{Pr}',
  '\\E': '\\mathbb{E}',
  '\\C': '\\mathbb{C}',
  '\\R': '\\mathbb{R}',
  '\\N': '\\mathbb{N}',
  '\\Z': '\\mathbb{Z}',
  '\\I': '\\mathbb{I}',
  '\\H': '\\mathcal{H}',
  '\\tensor': '\\otimes',
  '\\dagger': '\\dagger',
}
